# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 84a792b0a144989d42ac55235dc7810c9a89a1e0a116dc998ac0130ffdb0b9af55bf71f8be0a576fda27333f9b42b796f471b03b0ab9556ba616982816fff836

test:
  secret_key_base: ba11f79b8d2f8141d5aea3e4e9eeb5751401ec86cd2019d00e3c1f0fc56dcf0f342e6445f98b7ec4ef7176de43ae3633c3e041c0ab9b5b07278e75a0d2c1c228

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
